services:
  backend:
    build: .
    image: circle-on-backend:dev
    container_name: backend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ports:
      - "8080:8080"
    volumes:
      - ${IMAGE_STORAGE_PATH}:/app/images
      - ${LOG_STORAGE_PATH}:${LOG_PATH}
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_SES_ACCESS_KEY=${AWS_SES_ACCESS_KEY}
      - AWS_SES_SECRET_ACCESS_KEY=${AWS_SES_SECRET_ACCESS_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SIGNED_URL_SECRET_KEY=${SIGNED_URL_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOG_PATH=${LOG_PATH}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - TZ=Asia/Seoul

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend
    restart: always

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    environment:
      - EMAIL=${EMAIL}
    entrypoint: >
      sh -c "sleep 10 && certbot certonly \
      --webroot \
      --webroot-path=/var/www/certbot \
      --email ${EMAIL} \
      --agree-tos \
      --no-eff-email \
      -d api.circleondev.site"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ${PROMETHEUS_PATH}:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana


volumes:
  grafana-data: