name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build-only:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          SPRING_PROFILES_ACTIVE: ci